-- upsmfac_casa.dbo.Master_StudentProfile definition

-- Drop table

-- DROP TABLE upsmfac_casa.dbo.Master_StudentProfile;

CREATE TABLE upsmfac_casa.dbo.Master_StudentProfile (
	StudentProfileKey int IDENTITY(1,1) NOT NULL,
	CenterKey smallint NOT NULL,
	CourseKey smallint NOT NULL,
	AdmissionYear varchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	StudentName varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	StudentName_SurName varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	StudentFullName varchar(213) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DateOfBirth datetime NOT NULL,
	FatherName varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	FatherTitle varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FatherFullName varchar(106) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MotherTitle varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MotherName varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MotherFullName varchar(106) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ControlNo varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EnrollmentNo varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RollNo varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AdmissionDate datetime NULL,
	Title varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cast] varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IsFreedomFighter bit NULL,
	IsHandicap bit NULL,
	Gender varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ModifyCount smallint NULL,
	ExamSessionKey int NOT NULL,
	Inter_Subject varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Inter_Physics bit NULL,
	Inter_Chemistry bit NULL,
	Inter_Biology bit NULL,
	Inter_Math bit NULL,
	Inter_Art bit NULL,
	Inter_Commerce bit NULL,
	Inter_Other bit NULL,
	Inter_Percent float NULL,
	Exam_BoardKey smallint NULL,
	IntermediateSubjects varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	IntermediateEnglishSubject varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HighSchool_RollNo varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	HighSchool_PassingYear varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Intermediate_RollNo varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Intermediate_PassingYear varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ContactNo varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EmailId varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	AadhaarNo varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Address varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	District varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PinCode varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	StateKey smallint NULL,
	CountryKey smallint NULL,
	State varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Photo_Sign_Path varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PhotoPath varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	SignaturePath varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FinancialYear varchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	StudentProfileStatus smallint NULL,
	FormVerifiedBy int NULL,
	FormVerifiedOn datetime NULL,
	FormVerifierComment varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CancelCauseId smallint NULL,
	CancelDetails varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DiplomaDate datetime NULL,
	DiplomaNo int NULL,
	DiplomaDeclaredBy int NULL,
	DiplomaDeclaredOn datetime NULL,
	RegnReceiptNo varchar(250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	RegnReceiptDate datetime NULL,
	CreatedBy int NULL,
	CreatedOn datetime NULL,
	LastModifiedBy int NULL,
	LastModifiedOn datetime NULL,
	IsActive bit NULL,
	BarCode varchar(9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DeletedBy int NULL,
	DeletedOn datetime NULL,
	CONSTRAINT PK_Master_StudentProfile PRIMARY KEY (StudentProfileKey)
);
 CREATE NONCLUSTERED INDEX IX_Master_StudentProfile ON dbo.Master_StudentProfile (  BarCode ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
 CREATE NONCLUSTERED INDEX IX_Master_StudentProfile_1 ON dbo.Master_StudentProfile (  CenterKey ASC  , CourseKey ASC  )  
	 WITH (  PAD_INDEX = OFF ,FILLFACTOR = 100  ,SORT_IN_TEMPDB = OFF , IGNORE_DUP_KEY = OFF , STATISTICS_NORECOMPUTE = OFF , ONLINE = OFF , ALLOW_ROW_LOCKS = ON , ALLOW_PAGE_LOCKS = ON  )
	 ON [PRIMARY ] ;
